/**
 * NextAuth.js API Route Handlers
 *
 * This file exports the NextAuth.js API route handlers for authentication endpoints.
 * It handles all authentication-related API requests including:
 * - Sign in/out requests
 * - OAuth provider callbacks
 * - Session management
 * - Token refresh
 *
 * @fileoverview NextAuth.js API route handlers
 * @author WEBDEV.blog Team
 * @version 1.0.0
 */

import { handlers } from "@/auth";

/**
 * Export NextAuth.js handlers for GET and POST requests
 * These handlers are automatically generated by NextAuth.js and handle:
 * - GET: Session retrieval, provider callbacks
 * - POST: Sign in/out requests, token refresh
 */
export const { GET, POST } = handlers;
